### ISSUE TITLE
`exec` -> `execFile`

### ISSUE THREAD

**Issue by phated** [robrich/gulp-exec#23]
The `child_process.exec` command is insecure and it is usually suggested that `child_process.execFile` be used instead.  Thoughts on switching it?

@contra @sindresorhus

**Comment by sindresorhus** [comment]
`exec` sends the command to the shell, `execFile` sends it directly to the process. The former is more insecure indeed, but has a lot more possibilities. You can only do simple stuff with `execFile`: `git clone`, while with `exec` you can do `git status | grep foo && git clone; echo done`.

I think both has a merit, but `execFile` should be preferred whenever possible. Might make sense to have this task support both, but with a big warning about preferring `execFile` whenever possible and the dangers of `exec`.

**Comment by robrich** [comment]
In general, don't use gulp-exec, use child_process.exec or child_process.spawn directly.

**Comment by phated** [comment]
That's what we suggest but people are still going to use this plugin, so it's not really valid to dismiss the issue for that reason.

**Comment by robrich** [comment]
https://ant.apache.org/manual/Tasks/exec.html
