### ISSUE TITLE
Allow outputting stderr, stdout even if the exec'd command fails with a nonzero exit code

### ISSUE THREAD

**Issue by b0ri5** [robrich/gulp-exec#24]
I couldn't figure out how to do this using gulp-exec. Is there a way to?

If I run a command that exits with a nonzero exit code I get the following vague output with no mention of the stdout or stderr of the failed command:

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Command failed: 
    at ChildProcess.exithandler (child_process.js:637:15)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:743:16)
    at Process.ChildProcess._handle.onexit (child_process.js:810:5)

**Comment by robrich** [comment]
Use gulp-exec reporters -- similar to gulp-jshint's reporters methodology.  See also README.md and https://github.com/robrich/gulp-exec/blob/master/index.js#L43
