### ISSUE TITLE
Possible to parse report to then set variables?

### ISSUE THREAD

**Issue by petemounce** [robrich/gulp-exec#28]
I need to extract some text from stdout and make that available to subsequent & separate gulp tasks - how should I go about that? Both the parse & extract part, and the make-available part (maybe write to a file?).

**Comment by robrich** [comment]
Sounds like you need to use child_process.exec() directly, then in the
callback, set the vars and write the files. The readme walks through using
child_prices directly, and the rest is just node. Or you could just copy
the contents from index.js as a starting point.
