### ISSUE TITLE
gulp-exec not writing anything to console

### ISSUE THREAD

**Issue by miparnisari** [robrich/gulp-exec#29]
My task is similar to this: 

``` javascript
gulp.task('db', function () {
  return gulp.src('./**/**')
    .pipe(exec('node ./scripts/dropDb.js'))
    .pipe(exec('node ./scripts/addRandomUsers.js'))
    .pipe(exec.reporter());
})
```

The script dropDb contains the following:

``` javascript
var generateDb = function() {  
  // do something
  Promise.resolve();
});
generateDb().then(function() {
  console.log("done!");
}).catch(function (err) {
  console.error(err);
}).finally(function () {
  process.exit();
});
```

The problem I have is that nothing is written to the console, and I have no idea what it is happening because it never seems to end.

**Comment by robrich** [comment]
I'm guessing either nothing matched the glob or nothing is draining the pipe so nothing starts it.  Try this and see if you get console output:

 
gulp.task('db', function () {
  return gulp.src('./**/**')
    .pipe(through2.obj(function (file, enc, cb) {
      console.log(file.path);
      this.push(file);
      cb(null);
    })
    .pipe(exec('node ./scripts/dropDb.js'))
    .pipe(exec('node ./scripts/addRandomUsers.js'))
    .pipe(exec.reporter());
})

If that works, try this:

var childProcess = require('child_process');
 
gulp.task('db', function () {
  return gulp.src('./**/**')
    .pipe(through2.obj(function (file, enc, cb) {
      console.log(file.path);
      this.push(file);
      cb(null);
    })
    .pipe(through2.obj(function (file, enc, cb) {
       var that = this;
       childProcess.exec('node ./scripts/dropDb.js '+file.path, function (err) {
         that.push(file);
         cb(err);
       });
       this.push(file);
    })
    .pipe(exec('node ./scripts/addRandomUsers.js'))
    .pipe(exec.reporter());
}) 

If that works, try this:

var dropDb = require('./scripts/dropDb');

gulp.task('db', function () {
  return gulp.src('./**/**')
    .pipe(through2.obj(function (file, enc, cb) {
      console.log(file.path);
      this.push(file);
      cb(null);
    })
    .pipe(through2.obj(function (file, enc, cb) {
       var that = this;
       dropDb(file.path, function (err) {
         that.push(file);
         cb(err);
       });
       this.push(file);
    })
    .pipe(exec('node ./scripts/addRandomUsers.js'))
    .pipe(exec.reporter());
})

If that works, try this:

var dropDb = require('./scripts/dropDb');

var addRandomUsers = require('./scripts/addRandomUsers');

gulp.task('db', function (cb) {
  dropDb(function (err) {
    if (err) {
      return cb(err);
    }
    addRandomUsers(cb);
  });
});

**Comment by miparnisari** [comment]
Ok so I only tried your 1st suggestion and it works very strangely. It starts printing out filenames and folders, then executes the script, then again a list of filenames, then it executes again... it never seems to end.

**Comment by robrich** [comment]
You are correct. I incorrectly put `this.push(file);` and
`that.push(file);`. This will double the files flowing through the pipe.
Take out `this.push(file);`.

**Comment by miparnisari** [comment]
I'm getting this same issue again:

The task is this:
```javascript
gulp.task('test', ['pre-test'], function () {
  return gulp.src('test/**/*.js')
    .pipe(through2.obj(function (file, enc, cb) {
      console.log(file.path);
      cb(null);
    }))
    .pipe(exec('mocha --colors test/*.js | bunyan -o short --color'))
    .pipe(exec.reporter())
    .pipe(istanbul.writeReports())
    .pipe(istanbul.enforceThresholds({ thresholds: { global: 90 } }));
});
```

And the output is this:

```bash
λ gulp test
[11:47:26] Using gulpfile ~\Documents\project\backend\gulpfile.js
[11:47:26] Starting 'pre-test'...
[11:47:27] Finished 'pre-test' after 1.06 s
[11:47:27] Starting 'test'...
C:\Users\miparnisari\Documents\project\backend\test\baseMocks.js
C:\Users\miparnisari\Documents\project\backend\test\basePromise.js
C:\Users\miparnisari\Documents\project\backend\test\helpers\cargapos.js
C:\Users\miparnisari\Documents\project\backend\test\helpers\cbu.js
// ...
// more files...
// ...
----------|----------|----------|----------|----------|----------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
----------|----------|----------|----------|----------|----------------|
All files |      100 |      100 |      100 |      100 |                |
----------|----------|----------|----------|----------|----------------|


=============================== Coverage summary ===============================
Statements   : 100% ( 0/0 )
Branches     : 100% ( 0/0 )
Functions    : 100% ( 0/0 )
Lines        : 100% ( 0/0 )
================================================================================
[11:47:27] Finished 'test' after 160 ms
```

So it looks like `mocha` isn't even running. I'm using Gulp 3.9.1 BTW.

**Comment by robrich** [comment]
Add `this.push(file);`

**Comment by miparnisari** [comment]
Ok, I've added it. Now the tests run but (a) the logs come out on screen only after all the tests run and (b) the coe coverage tool isn't running. Does `exec` return a stream?

**Comment by robrich** [comment]
This code:

gulp.task('test', ['pre-test'], function () {
  return gulp.src('test/**/*.js')
    .pipe(through2.obj(function (file, enc, cb) {
      console.log(file.path);

      this.push(file);
      cb(null);
    }))
    .pipe(exec('mocha --colors test/*.js | bunyan -o short --color'))
    .pipe(exec.reporter())
    .pipe(istanbul.writeReports())
    .pipe(istanbul.enforceThresholds({ thresholds: { global: 90 } }));
});


Means this:


for every js file in the test folder

- log the filename

- run mocha on all test files (not this file)

- output the results

- run Istanbul's report

- validate the thresholds


Note that you're rerunning the tests for each file. Since you're not
draining the pipe, it probably runs 16 times max.
