### ISSUE TITLE
Setting current working directory when executing command

### ISSUE THREAD

**Issue by mmc41** [robrich/gulp-exec#32]
I need to be able to execute "npm install" on a number of subfolders, for which I need to change current working dir to a specific folder when execution my command. Unfortunately, I can find no way to do this in gulp-exec ?

**Comment by robrich** [comment]
The second argument passed to gulp-exec is the options passed directly to child-process.exec.  (see https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback)  You're looking for the `cwd` property there.
