### ISSUE TITLE
child process closing immediately

### ISSUE THREAD

**Issue by Arro** [robrich/gulp-exec#35]
If you're not familiar with icecast, it's a multimedia server.   

When I run `icecast -c ./icecast/icecast.xml` in the terminal, it starts an icecast server, which stays alive.

So I want to run that command alongside my node.js process, every time I run `gulp`.

I added the following to my gulpfile.

    import exec from 'gulp-exec'

    ...

    const icecastDir = path.resolve(`${__dirname}/icecast/`)

    ...

    gulp.task(`icecast`, () => {
      return exec(`/usr/local/bin/icecast -c ${icecastDir}/icecast.xml`)
        .on(`data`, () => {
          console.log(`data`)
        }) 
        .on(`error`, () => {
          console.log(`error`)
        }) 
        .on(`end`, () => {
          console.log(`end`)
        }) 
        .on(`close`, () => {
          console.log(`error`)
        }) 
        .on(`readable`, () => {
          console.log(`readable`)
        }) 
    })

When I run the command `gulp icecast` in my terminal, gulp says `Starting 'icecast'...` and then immediately terminates.  None of the callbacks fire.  I'd really like it to stay alive until I cmd-c the gulp process.

**Comment by robrich** [comment]
You're not piping any filenames into it.  In this case, don't use `gulp-exec` and use [`child_process#exec`](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback) directly.

**Comment by Arro** [comment]
Thx for this response, by the way.  Closing.
