### ISSUE TITLE
stuck forever at "gulp task"

### ISSUE THREAD

**Issue by abhijeet1995** [robrich/gulp-exec#41]
`gulp.task('task', function (cb) {

exec('ng test -cc', function (err, stdout, stderr) {

console.log(stdout);

console.log(stderr);

cb(err);
});

})`

**Comment by robrich** [comment]
You would be better served with child_process.exec. gulp-exec assumes
you've got a gulp.src(...) piping filenames into the command. Since you're
only running a single command, just run that one command.
