### ISSUE TITLE
Can't continue to pipe output of exec

### ISSUE THREAD

**Issue by db-ryan** [robrich/gulp-exec#42]
Hiya! I am trying to use gulp-exec to run a PHP compilation that continues to stream to a minified then a file.  I can't seem to get this to work though.  I am sure there is some simple answer that I am just missing.  I see the output gets put on stdout with the .reporter function but I'm not sure how to get that back into a stream.

```
/* ******************************************************************
 * Basic PHP Compile Function
 * *****************************************************************/
function phpBuild(phpFilename, htmlFilename) {
  return () => {
    gulp.src(phpFilename)
      .pipe(exec('php <%= file.path %>'))
      .pipe(htmlMin({ collapseWhitespace: true }))
      .pipe(exec.reporter())
      .pipe(rename(path.basename(htmlFilename)))
      .pipe(gulp.dest(path.dirname(htmlFilename)));
  } // return
} // phpBuild
```

**Comment by robrich** [comment]
When you run this:

    gulp.src(phpFilename)
      .pipe(exec('php <%= file.path %>'))
      .pipe(htmlMin({ collapseWhitespace: true }))

what you've said is "take the content of the phpFilename, run php on that file, then take the contents of the original file and run htmlMin then …

Try this:

const execSync = require('child_process').execSync;

…

function phpBuild(phpFilename, htmlFilename) {
  return () => {
    execSync('php '+phpFilename' > tmpfilename'); // <- if I pushed harder I could get this async
    return gulp.src('tmpfilename')
      .pipe(htmlMin({ collapseWhitespace: true }))
      .pipe(rename(path.basename(htmlFilename)))
      .pipe(gulp.dest(path.dirname(htmlFilename)));
  } // return
} // lessBuild

**Comment by db-ryan** [comment]
Thanks Rob. We had a version like that earlier but thought this would be "prettier" if we could get it to work.

**Comment by db-ryan** [comment]
Here is where we ended up with this for anyone interested....

`/* ******************************************************************
 * Basic PHP Compile Function
 * *****************************************************************/
function phpBuild(phpFilename, htmlFilename) {
  return () => {
    // Create a temp 'filename' that we will use for Vinyl
    const tmpFilename = htmlFilename + ".tmp";

    // Execute the php command and create a Vinyl file
    exec('php ' + phpFilename, (err, stdout, stderr) => {
      file(tmpFilename, stdout, {src: true })
        // Usualy gulping
        .pipe(plumber())
        .pipe(htmlMin({ collapseWhitespace: true }))
        .pipe(rename(path.basename(htmlFilename)))
        .pipe(gulp.dest(path.dirname(htmlFilename)));
    }); // exec php
  } // return
} // phpBuild`

**Comment by robrich** [comment]
The other way to go could be this:

 

const exec = require('child_process').exec;

const through2 = require('through2');

 

function phpBuild(phpFilename, htmlFilename) {

  return gulp.src(phpFilename)

    .pipe(through2.obj(function (file, enc, cb) {

      exec('php '+phpFilename, function (err, stdout, stderr) {

        // FRAGILE: assume no error

        file.contents = new Buffer(stdout);

        cb();

      });

    }))

    .pipe(htmlMin({ collapseWhitespace: true }))

    .pipe(rename(path.basename(htmlFilename)))

    .pipe(gulp.dest(path.dirname(htmlFilename)));

} // phpBuild

Or look at opt.pipeStdout from https://github.com/robrich/gulp-exec/blob/master/index.js#L36

**Comment by db-ryan** [comment]
Awesome. That seems more in line with being the "gulp" way. Thanks for the help.

**Comment by db-ryan** [comment]
Where we ended up with this:

```
/* ******************************************************************
 * Basic PHP Compile Function
 * *****************************************************************/
function phpBuild(phpFilename, htmlFilename) {
  return () => {
    gulp.src(phpFilename)
      .pipe(plumber())
      .pipe(through2.obj((file, enc, cb) => {
        exec('php ' + phpFilename, (err, stdout, stderr) => {
          if (err) { gutil.log(err); }
          file.contents = new Buffer(stdout);
          cb(err, file);
        }); // exec
      })) // php pipe
      .pipe(htmlMin({ collapseWhitespace: true }))
      .pipe(rename(path.basename(htmlFilename)))
      .pipe(gulp.dest(path.dirname(htmlFilename)));
  } // return
} // phpBuild
```
