### ISSUE TITLE
Incorrect handling of binary content from stdout

### ISSUE THREAD

**Issue by Glebka** [robrich/gulp-exec#43]
Hi.

``gulp-exec`` plugin corrupts binary data that come from ``stdout``. See example ``gulpfile.js`` below.

```js
gulp.task("extractAlpha", function() {
  var options = {
    continueOnError: false,
    pipeStdout: true,
    encoding: 'binary'
  };
  return gulp
    .src("./*.png")
    .pipe(
        exec(
          "convert <%= file.path %> -alpha extract -",
          options
        )
      )    
    .pipe(gulp.dest('out/'));    
});
```

Here you can see ``extractAlpha`` task that uses ``convert`` CLI tool from ImageMagick distribution. It extracts alpha channel as a separate image and outputs the result to the ``stdout``.
When I run this task I get corrupted image in the output folder. Note, that I've specified ``encoding: 'binary'`` option for ``exec`` but it doesn't help.

The root cause of the issue is here: https://github.com/robrich/gulp-exec/blob/8f934d9316b917c9b268515a50472a299c8b5300/index.js#L38
Providing an encoding when creating a ``Buffer`` should fix the issue.

Will create PR for this soon.

This issue occurs on:
Windows 8.1, NodeJS v8.11.2

**Comment by robrich** [comment]
Thanks for the PR.  It also sounds like you've outgrown gulp-exec as gulp spends a lot of time loading the file contents and piping things around which you're not using.  You may want to swap to:

```
const exec = require('child_process').exec;
const glob = require('glob');
const promisify = require('util').promisify;

const execAsPromise = promisify(exec);

gulp.task("extractAlpha", function(cb) {
  glob("./*.png", function (err, files) {
    let promises = files.map(file => execAsPromise(`convert ${file} -alpha extract > out/${file}`));
    Promise.all(promises).then(cb);
  });
});
```

**Comment by Glebka** [comment]
Thanks for advice :) I am new to gulp and just playing with it to understand how it works. 
Well, actually I am trying to modify the code of [that guy](https://github.com/anko/image-to-box2d-body) because he uses ``make`` for generating shapes from png images. Just trying to replace ``make`` with ``gulp`` because I am too lazy to install ``make`` on Windows :)
