### ISSUE TITLE
Windows & Path

### ISSUE THREAD

**Issue by TigersWay** [robrich/gulp-exec#45]
Hi,
Anyone could confirm the `node_modules\bin` path is working under windows?
```
.pipe($.exec('node_modules\\.bin\\lessc <%= file.path %>', {pipeStdout: true}))
.pipe($.exec('lessc <%= file.path %>', {pipeStdout: true}))
```
The first one is working, the second is not!
Thanks

**Comment by robrich** [comment]
Yes.  It computes relative paths relative to the current file you're working in.  So move this file to the root of your project and it'll work fine.  Put it in a sub directory, and it won't.  Since you're not using the file contents, you may have more success and build speed using `glob` and `vinyl-fs` and `child_process.exec` directly.

**Comment by TigersWay** [comment]
I'm clearly (I thought) using the file content which is why I add to add `{pipeStdout: true}`.
And I still cannot use the command line batchs installed with some packages... without giving the path `node_modules\.bin` . I thought it was done  #19

**Comment by TigersWay** [comment]
Just pushed one... well a very simplified one, but "working" one [lessjs-3.x](https://github.com/TigersWay/lessjs-3.x)
You'll see 3 lines in the gulpfile.js / 'testing' task 
```
    //.pipe($.less())
    //.pipe($.exec('lessc.cmd <%= file.path %>', {pipeStdout: true}))
    .pipe($.exec('node_modules\\.bin\\lessc <%= file.path %>', {pipeStdout: true}))
```
the first one, alone, is working of course.
The second one, still alone, should work but does not.
To be sure, the third one with the path, again alone, is working fine.

Trying to beta test different things, starting with less these days, i'd love to make `exec` work.

**Comment by robrich** [comment]
I think I have one too many `..` when prepending the path.  https://github.com/robrich/gulp-exec/commit/cc4338841c698709fbdf65bc8c8880e592deba8e may fix it, though I'm not sure what it'll break.  Try opening `node_modules\gulp-exec\prependPath.js` and changing line 14 to `var newPath = path.resolve(path.join(__dirname, '..', '.bin'));`.  If this solves the issue, I'll push a new version to npm so it'll work everywhere.

**Comment by TigersWay** [comment]
Working fine for me now!

**Comment by robrich** [comment]
Published 3.0.2 to npm.  Try upgrading and see if this resolves the concern.

**Comment by TigersWay** [comment]
It seems I have more troubles than I thought between **pnpm & nvm-windows**. the installation folders are messed up.
I need to clear these first to give an honest and precise answer :-(

**Comment by TigersWay** [comment]
Back at last.....
It seems that a lot of different tools have very different ideas about what they should care about.

Nevertheless I checked again on the same repo and with 1 or 2 '..' ( cc43388 ) it stills does not work for me. And as you wrote I felt invited to use npx (or pnpx in my case) to make it better:

`.pipe($.exec('pnpx lessc <%= file.path %>', {pipeStdout: true}))`

and will continue to do so.
I have to let you decide to close this issue then, or not...
Thanks anyway

**Comment by robrich** [comment]
Weird. Then I'm not sure I was able to reproduce your issue. With the
GitHub repo it worked for me after the change. Is there more to your
scenario that I didn't see? Is there version pinned? (E.g. did reinstalling
just reinstall the old version?)

>
If npx works for you, I guess works is better than perfect, and we can call
it resolved.

**Comment by ve3** [comment]
Is it working on Windows? Because I try this code but not working.
```js
function getPublicPath(cb) {
    let exec = require('gulp-exec');

    exec('mkdir aa');
    cb();
}

exports.default = series(
    getPublicPath
);
```

No folder created.

**Comment by robrich** [comment]
gulp-exec is meant to be used for each file in a  gulp.src. If you just
want a single directory created, use mkdirp.

**Comment by ve3** [comment]
I did not want a single directory create but I just test it that it is really working because I did not get any result from the real command using exec.

**Comment by robrich** [comment]
Try this:

gulp.src('**').pipe(gulpExec('mkdir aa'));

In your example, you set up the pipeline but piped exactly zero files
through so it was correctly executed exactly zero times.

**Comment by ve3** [comment]
I've changed to this to make it working.
```js
function getPublicPath(cb) {
    let exec = require('child_process').exec

    exec('php myphpfile.php', (err, stdout, stderr) => {
        // work with stdout.
        // ...
        cb(err);
    });
}
exports.default = series(
    getPublicPath,
    // my_other_functions
);
```

**Comment by robrich** [comment]
Glad you got it solved.
